[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss12"

    [buildPlans.IosevkaCustom.variants.design]
    eight = "crossing-asymmetric"
    zero = "tall-slashed"
    capital-q = "crossing"
    f = "tailed-crossbar-at-half-ascender-height"
    g = "single-storey-earless-corner"
    i = "semi-tailed"
    l = "serifed-semi-tailed"
    x = "semi-chancery-straight-serifless"
    y = "curly-turn-serifless"
    asterisk = "turn-hex-low"
    dollar = "through"
    cent = "through"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

    [buildPlans.IosevkaCustom.variants.oblique]
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 1.6
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 10.4
shape = "italic"
menu = "italic"
css = "italic"
