[buildPlans.iosevkacustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.iosevkacustom.variants]
  inherits = "ss12"

    [buildPlans.iosevkacustom.variants.design]
    eight = "crossing-asymmetric"
    zero = "tall-slashed"
    capital-q = "crossing"
    capital-v = "straight-serifed"
    capital-w = "straight-almost-flat-top-serifed"
    f = "tailed-crossbar-at-half-ascender-height"
    g = "single-storey-earless-corner"
    i = "semi-tailed"
    l = "serifed-semi-tailed"
    v = "curly-serifless"
    x = "chancery"
    y = "curly-turn-serifless"
    lower-nu = "casual-serifed"
    asterisk = "turn-hex-low"
    dollar = "through"
    cent = "through"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

	    [buildPlans.iosevkacustom.variants.oblique]
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

[buildPlans.iosevkacustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevkacustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevkacustom.slopes.Upright]
angle = 1.8
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevkacustom.slopes.Italic]
angle = 10.6
shape = "italic"
menu = "italic"
css = "italic"
