[buildPlans.iosevkacustom]
family = "Iosevka Custom"
# "fixed" から "term" に戻すとリガチャが有効になります
spacing = "term"
serifs = "sans"
no-cv-ss = false
# リガチャを明示的に有効化
no-ligation = false
  



 [buildPlans.IosevkaCustom.variants]
  inherits = "ss12"

    [buildPlans.IosevkaCustom.variants.design]
    zero = "tall-slashed"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifed-both-sides"
    capital-p = "closed-serifless"
    capital-q = "crossing-baseline"
    a = "double-storey-tailed"
    f = "tailed-crossbar-at-half-ascender-height"
    g = "double-storey"
    i = "semi-tailed"
    l = "tailed"
    q = "tailed-motion-serifed"
    dollar = "interrupted"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-plus-chain = "with-notch"

    [buildPlans.IosevkaCustom.variants.italic]
    zero = "tall-slashed"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifed-both-sides"
    capital-p = "closed-serifless"
    capital-q = "crossing-baseline"
    a = "double-storey-tailed"
    f = "tailed-crossbar-at-half-ascender-height"
    g = "double-storey"
    i = "semi-tailed"
    l = "tailed"
    q = "tailed-motion-serifed"
    dollar = "interrupted"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-plus-chain = "with-notch"

    [buildPlans.IosevkaCustom.variants.oblique]
    zero = "tall-slashed"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifed-both-sides"
    capital-p = "closed-serifless"
    capital-q = "crossing-baseline"
    a = "double-storey-tailed"
    f = "tailed-crossbar-at-half-ascender-height"
    g = "double-storey"
    i = "semi-tailed"
    l = "tailed"
    q = "tailed-motion-serifed"
    dollar = "interrupted"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-plus-chain = "with-notch"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "clike"
  
  
[buildPlans.iosevkacustom.weights.Regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevkacustom.slopes.Upright]
angle = 2.5
shape = "upright"
menu  = "upright"
css   = "normal"
