name: Build Custom Iosevka
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y ttfautohint
          npm install
         - name: Build
        # --plan-file オプションを追加して、TOMLファイルを直接指定します
        run: npm run build -- Iosevka-Custom --plan-file private-build-plans.toml --contents dist/
        - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: iosevka-custom-font
          path: dist/
